/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/airplane/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


const PROP_SPEED = 6

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/models/airplane/model.glb')

  const prop = useRef()

  useFrame((state, delta) => {
    prop.current.rotation.x += delta * PROP_SPEED
  })


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} />
      <mesh ref={prop} geometry={nodes.PUSHILIN_Plane_Helix.geometry} material={materials.plane} position={[1.09, 0.23, 0]} />
    </group>
  )
}

useGLTF.preload('/models/airplane/model.glb')
